version: '3.8'

services:
  nest-pm2-docker:
    image: nest-pm2-docker
    build: .
    ports:
      - target: 4000
        published: 4000
        protocol: tcp 
    healthcheck:
      test: curl -f http://localhost:4000 || exit 1
      interval: 30s
      timeout: 5s
      retries: 3

