version: '3.8'

services:
  nest-pm2-docker:
    image: nest-pm2-docker
    build: .
    ports:
      - target: 4000
        published: 4000
        protocol: tcp 
    healthcheck:
        test: ["CMD", "/usr/local/bin/healthcheck" ]
        interval: 30s
        timeout: 5s
        retries: 3
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - target: 6379
        published: 6379
        protocol: tcp


