version: '3.8'

services:
  nest-pm2-docker:
    image: nest-pm2-docker
    build: .
    ports:
      - target: 4000
        published: 4000
        protocol: tcp 
    healthcheck:
        test: ["CMD", "/usr/local/bin/healthcheck" ]
        interval: 30s
        timeout: 5s
        retries: 3
    networks:
      - myNetWork
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    container_name: redis
    networks:
      - myNetWork
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD" 
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
    env_file:
      - redis.env
    hostname: redis
  mariadb:
    image: mariadb
    container_name: "mariadb"
    hostname: mariadb
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
    env_file:
      - mariadb.env
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - myNetWork
networks:
  myNetWork:
    name: myNetWork

# 不給名稱預設是nestjs_environment_default
